-- GENERATED by packages/payroll-engine/scripts/gen_seed.ts. Do not edit by hand; change the engine tables and regenerate.
-- Figures marked confidence low/medium must be verified against the state notification before go-live.

insert into public.statutory_rules (rule_key, value, effective_from, status, source, note, verified_on) values
  ('pf.wageCeiling', '15000'::jsonb, '2014-09-01', 'in_force', 'EPF Scheme 1952 (statutory wage ceiling)', null, '2026-09-19'),
  ('pf.wageCeiling', '25000'::jsonb, '2026-09-17', 'announced', 'Union Cabinet decision, 16 Sep 2026 (pmindia.gov.in)', 'Approved by Cabinet on 16 Sep 2026. The official release gives no effective date; one secondary source says 17 Sep 2026. Gazette notification pending. Publish as in_force only after notification.', '2026-09-19'),
  ('pf.employeeRate', '0.12'::jsonb, '1952-11-01', 'in_force', 'EPF Scheme 1952', null, '2026-09-19'),
  ('pf.epsRate', '0.0833'::jsonb, '1995-11-16', 'in_force', 'EPS 1995 (8.33%)', null, '2026-09-19'),
  ('pf.employerTotalRate', '0.12'::jsonb, '1952-11-01', 'in_force', 'EPF Scheme 1952 (EPF 3.67% + EPS 8.33%)', null, '2026-09-19'),
  ('pf.edliRate', '0.005'::jsonb, '2000-01-01', 'in_force', 'EDLI Scheme 1976 contribution 0.5% (current rate; historical effective date not tracked)', null, '2026-09-19'),
  ('pf.adminRate', '0.005'::jsonb, '2000-01-01', 'in_force', 'EPF admin charges 0.5% (current rate; historical effective date not tracked)', null, '2026-09-19'),
  ('pf.adminMin', '500'::jsonb, '2000-01-01', 'in_force', 'EPF admin charges minimum Rs 500 per establishment per month (current; historical effective date not tracked)', null, '2026-09-19'),
  ('esi.wageCeiling', '21000'::jsonb, '2017-01-01', 'in_force', 'ESI Act notification, Rs 21,000 per month', null, '2026-09-19'),
  ('esi.employeeRate', '0.0075'::jsonb, '2019-07-01', 'in_force', 'ESIC rates from 1 Jul 2019 (0.75%)', null, '2026-09-19'),
  ('esi.employerRate', '0.0325'::jsonb, '2019-07-01', 'in_force', 'ESIC rates from 1 Jul 2019 (3.25%)', null, '2026-09-19'),
  ('esi.dailyWageExempt', '176'::jsonb, '2019-07-01', 'in_force', 'ESIC: employee share waived at average daily wage up to Rs 176', null, '2026-09-19'),
  ('bonus.eligibilityCeiling', '21000'::jsonb, '2025-11-21', 'in_force', 'Code on Wages 2019 s.26(1); MoLE notification Aug 2026, effective 21 Nov 2025', null, '2026-09-19'),
  ('bonus.calcFloor', '7000'::jsonb, '2025-11-21', 'in_force', 'MoLE notification Aug 2026: higher of Rs 7,000 or applicable minimum wage', null, '2026-09-19'),
  ('bonus.minPct', '8.33'::jsonb, '2025-11-21', 'in_force', 'Code on Wages 2019 s.26', null, '2026-09-19'),
  ('bonus.maxPct', '20'::jsonb, '2025-11-21', 'in_force', 'Code on Wages 2019 s.26', null, '2026-09-19'),
  ('gratuity.maxAmount', '2000000'::jsonb, '2018-03-29', 'in_force', 'Payment of Gratuity (Amendment) Act 2018; carried into Code on Social Security 2020', null, '2026-09-19'),
  ('gratuity.minYearsPermanent', '5'::jsonb, '2025-11-21', 'in_force', 'Code on Social Security 2020', null, '2026-09-19'),
  ('gratuity.minYearsFixedTerm', '1'::jsonb, '2025-11-21', 'in_force', 'Code on Social Security 2020: pro-rata gratuity after 1 year for fixed-term employees', null, '2026-09-19'),
  ('wage.excludedCapPct', '0.5'::jsonb, '2025-11-21', 'in_force', 'Code on Wages 2019 s.2(y) proviso: excluded payments above 50% are added back to wages', null, '2026-09-19')
on conflict do nothing;

insert into public.professional_tax_slabs (state_code, frequency, gross_from, gross_to, amount, february_amount, women_exempt_up_to, annual_cap, deduction_months, confidence, verified_on, source) values
  ('MH', 'monthly', 0, 7500, 0, null, 25000, 2500, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Slabs cross-checked in two secondary sources. Women exemption up to Rs 25,000 is flagged "confirm current notification" by one source; confirm before go-live.'),
  ('MH', 'monthly', 7501, 10000, 175, null, 25000, 2500, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Slabs cross-checked in two secondary sources. Women exemption up to Rs 25,000 is flagged "confirm current notification" by one source; confirm before go-live.'),
  ('MH', 'monthly', 10001, null, 200, 300, 25000, 2500, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Slabs cross-checked in two secondary sources. Women exemption up to Rs 25,000 is flagged "confirm current notification" by one source; confirm before go-live.'),
  ('KA', 'monthly', 0, 24999, 0, null, null, 2500, null, 'medium', '2026-09-19', 'saachihrms.com Karnataka PT 2026; calcguru.in Karnataka PT; greythr.com Karnataka Amendment Act 2025 notice | Amendment Act 2025 (from 1 Apr 2025): Rs 200 a month, Rs 300 in February. One source says nil "up to" Rs 25,000, two say Rs 25,000 "and above" is taxed: the exact boundary at Rs 25,000 needs confirming. An aggregator page listing Rs 150 for Rs 25,001-41,666 contradicts the amendment and was disregarded.'),
  ('KA', 'monthly', 25000, null, 200, 300, null, 2500, null, 'medium', '2026-09-19', 'saachihrms.com Karnataka PT 2026; calcguru.in Karnataka PT; greythr.com Karnataka Amendment Act 2025 notice | Amendment Act 2025 (from 1 Apr 2025): Rs 200 a month, Rs 300 in February. One source says nil "up to" Rs 25,000, two say Rs 25,000 "and above" is taxed: the exact boundary at Rs 25,000 needs confirming. An aggregator page listing Rs 150 for Rs 25,001-41,666 contradicts the amendment and was disregarded.'),
  ('TN', 'half_yearly', 0, 21000, 0, null, null, 2500, '{9,3}'::int[], 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Half-yearly slab on half-year gross; paid by 30 Sep and 31 Mar. Single-source figures; confirm with Greater Chennai Corporation / local body notification.'),
  ('TN', 'half_yearly', 21001, 30000, 135, null, null, 2500, '{9,3}'::int[], 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Half-yearly slab on half-year gross; paid by 30 Sep and 31 Mar. Single-source figures; confirm with Greater Chennai Corporation / local body notification.'),
  ('TN', 'half_yearly', 30001, 45000, 315, null, null, 2500, '{9,3}'::int[], 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Half-yearly slab on half-year gross; paid by 30 Sep and 31 Mar. Single-source figures; confirm with Greater Chennai Corporation / local body notification.'),
  ('TN', 'half_yearly', 45001, 60000, 690, null, null, 2500, '{9,3}'::int[], 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Half-yearly slab on half-year gross; paid by 30 Sep and 31 Mar. Single-source figures; confirm with Greater Chennai Corporation / local body notification.'),
  ('TN', 'half_yearly', 60001, 75000, 1025, null, null, 2500, '{9,3}'::int[], 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Half-yearly slab on half-year gross; paid by 30 Sep and 31 Mar. Single-source figures; confirm with Greater Chennai Corporation / local body notification.'),
  ('TN', 'half_yearly', 75001, null, 1250, null, null, 2500, '{9,3}'::int[], 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Half-yearly slab on half-year gross; paid by 30 Sep and 31 Mar. Single-source figures; confirm with Greater Chennai Corporation / local body notification.'),
  ('TG', 'monthly', 0, 15000, 0, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('TG', 'monthly', 15001, 20000, 150, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('TG', 'monthly', 20001, null, 200, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('WB', 'monthly', 0, 10000, 0, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('WB', 'monthly', 10001, 15000, 110, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('WB', 'monthly', 15001, 25000, 130, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('WB', 'monthly', 25001, 40000, 150, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('WB', 'monthly', 40001, null, 200, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab; salarybox.in PT 2026-27 guide | Two secondary sources agree.'),
  ('GJ', 'monthly', 0, 5999, 0, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Single-source figures; gender-based exemptions not modelled.'),
  ('GJ', 'monthly', 6000, 8999, 80, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Single-source figures; gender-based exemptions not modelled.'),
  ('GJ', 'monthly', 9000, 11999, 150, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Single-source figures; gender-based exemptions not modelled.'),
  ('GJ', 'monthly', 12000, null, 200, null, null, 2400, null, 'medium', '2026-09-19', 'kredily.com/professional-tax-slab | Single-source figures; gender-based exemptions not modelled.');

insert into public.lwf_rates (state_code, months, employee_share, employer_share, confidence, verified_on, notes) values
  ('MH', '{6,12}'::int[], 25, 75, 'medium', '2026-09-19', 'Half-yearly (Jun, Dec). Lower wage slabs not modelled. Confirm.'),
  ('KA', '{12}'::int[], 50, 100, 'low', '2026-09-19', 'Annual (Dec). One source only; applicability reportedly widened to 10+ employees from 7 Jan 2026. Confirm amounts.'),
  ('TN', '{12}'::int[], 10, 20, 'low', '2026-09-19', 'Annual (Dec). One source only. Confirm amounts.'),
  ('TG', '{12}'::int[], 2, 5, 'medium', '2026-09-19', 'Annual (Dec).'),
  ('WB', '{6,12}'::int[], 3, 30, 'low', '2026-09-19', 'Half-yearly (Jun, Dec). Employer share is unusually high in the single source; confirm before use.'),
  ('GJ', '{6,12}'::int[], 6, 12, 'medium', '2026-09-19', 'Half-yearly (Jun, Dec).');
